//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\!dev\!Cookie Machine\res\Cookie Machine.rc
//
#define IDC_BTN_AMBIENT_COL             1
#define IDOK2                           3
#define IDR_MENU_MESH_VIS               4
#define IDR_MENU_CONTEXT                4
#define IDR_MENU_CONTEXT_OPERATIONS     4
#define IDC_ADD_RANGE                   4
#define IDOK3                           4
#define IDC_DEL_RANGE                   5
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define TIMER                           101
#define IDD_MAIN                        102
#define RENDERING_TIMER                 102
#define MEMORY_STAT_TIMER               103
#define SB                              104
#define ID_INDICATOR_PAGE               105
#define ID_INDICATOR_PAGE2              106
#define ID_INDICATOR_PAGE3              107
#define ID_INDICATOR_PAGE4              108
#define ID_INDICATOR_PAGE5              109
#define ID_INDICATOR_PAGE6              110
#define ID_INDICATOR_PAGE7              111
#define ID_DBL_CLICK_TIMER              112
#define IDR_HTML_SCRIPTINGDLG           114
#define FILE_SAVED_TIMER                116
#define IDT_FILEOPEN                    117
#define ID_TOOLBAR                      118
#define IDT_FILESAVE                    119
#define IDT_FILESAVEALL                 120
#define IDT_FILECONV_2EFN               121
#define IDT_FILECONV_2MSH               122
#define IDT_FILECONV_2SCN               123
#define IDB_TB_FILECONV_2EFN_HOT        124
#define IDT_UNDO                        126
#define IDT_REDO                        127
#define IDR_MAINFRAME                   128
#define IDT_SHOWALL                     128
#define IDR_MENU                        129
#define IDT_HIDEALL                     129
#define IDT_AXIS_ALIGN                  130
#define IDD_VALIDATING                  131
#define IDT_OBJ_PROPERTIES              131
#define IDT_SETTINGS                    132
#define IDT_RUN_ENGINE                  133
#define IDT_RUN_ENGINE_CURR             134
#define IDB_MESH                        135
#define IDT_HELP                        135
#define IDD_BASEDIALOG                  136
#define IDB_GROUP                       137
#define IDT_BINDS                       137
#define IDB_INFO                        138
#define IDT_SCRIPTS                     138
#define IDB_VAR                         139
#define IDT_FLOORS                      139
#define IDT_ENGINE_LOGS                 140
#define IDT_TEXT_RES                    141
#define IDB_MESH_DIS                    142
#define IDT_ENGINE_CONSOLE              142
#define IDB_ANIM                        143
#define ID_SCRIPTING_TIMER              144
#define IDB_MAT                         145
#define IDC_CURSOR_TRN                  146
#define IDT_RELOAD_SCENE                146
#define IDC_CURSOR1                     147
#define IDC_CURSOR_TRN_Z                147
#define IDT_RELOAD_MESHES               147
#define IDC_CURSOR_ROT                  148
#define IDT_STOP_ENGINE                 148
#define IDB_SEQUENCE                    149
#define IDD_ABOUT                       151
#define IDD_MODEL_NAME                  154
#define IDD_ANIMATION                   155
#define IDB_ANIM_ITEM                   156
#define IDD_SCALING                     158
#define IDD_OPTIONS                     159
#define IDB_LIGHT                       162
#define IDB_ANIM_DIS                    163
#define IDB_LIGHT_DIS                   164
#define IDB_NULL_ITEM                   166
#define IDR_MENU_RENDER_VIEW            170
#define IDI_IC_FILE_OPEN                172
#define IDI_ICON1                       173
#define IDR_ACCELERATOR                 176
#define IDD_BINDS                       178
#define IDB_BIND                        179
#define IDD_BIND                        180
#define IDB_GRID                        182
#define IDD_DIALOG1                     186
#define IDD_DIALOG2                     187
#define IDD_SCRIPTING                   187
#define IDB_SCRIPT                      188
#define IDB_TEXTURE                     189
#define IDB_ACT_OBJ                     190
#define IDB_LAYER_GEOM                  191
#define IDB_CAMSELECT                   192
#define IDB_EMPTY                       193
#define IDB1                            194
#define IDB_                            194
#define IDB_GROUP_INFO                  194
#define IDB_TEXTURE2                    196
#define IDD_HELP                        197
#define IDD_COLOR                       198
#define IDB_FOLDER                      199
#define IDD_IMPORT_2SCN                 200
#define IDD_REPLACE_WRN                 201
#define IDD_MATERIAL                    203
#define IDB_INFO2                       204
#define IDD_ANIM_SCRIPTING              206
#define IDD_POSITION_ROTATION_SCALE     207
#define IDB_NULL_ITEM_DIS               208
#define IDR_ACCELERATOR_SCRIPT_DLG      209
#define IDD_FILE_ASSOCIATIONS           210
#define IDD_QUICKBIND                   211
#define IDD_SCRIPT_SEARCH               212
#define IDB_TR_TRANS                    215
#define IDB_TR_SCALE                    216
#define IDB_TR_ROT                      217
#define IDB_CUST_PARAM_SET              218
#define IDB_CUST_PARAM                  219
#define IDB_TB_FILEOPEN                 220
#define IDB_TB_FILESAVEALL              221
#define IDB_TB_FILESAVE                 222
#define IDB_TB_FILEOPEN_DIS             223
#define IDB_TB_FILESAVE_DIS             224
#define IDB_TB_FILESAVEALL_DIS          225
#define IDB_TB_FILEOPEN_HOT             226
#define IDB_TB_FILESAVE_HOT             227
#define IDB_TB_FILESAVEALL_HOT          228
#define IDB_TB_FILECONV_2EFN            229
#define IDB_TB_FILECONV_2EFN_DIS        230
#define IDB_TB_FILECONV_2MSH            232
#define IDB_TB_FILECONV_2MSH_DIS        233
#define IDB_TB_FILECONV_2MSH_HOT        234
#define IDB_TB_FILECONV_2SCN            235
#define IDB_TB_FILECONV_2SCN_DIS        236
#define IDB_TB_FILECONV_2SCN_HOT        237
#define IDB_TB_REDO                     238
#define IDB_TB_REDO_DIS                 239
#define IDB_TB_REDO_HOT                 240
#define IDB_TB_UNDO                     241
#define IDB_TB_UNDO_DIS                 242
#define IDB_TB_UNDO_HOT                 243
#define IDB_TB_SHOWALL                  244
#define IDB_TB_HIDEALL                  245
#define IDB_TB_AXIS_X                   246
#define IDB_TB_AXIS_XY                  247
#define IDB_TB_AXIS_XZ                  248
#define IDB_TB_AXIS_Y                   249
#define IDB_TB_AXIS_YZ                  250
#define IDB_TB_AXIS_Z                   251
#define IDR_MENU_AXIS                   252
#define IDB_TB_OBJPROP                  253
#define IDB_TB_OBJPROP_DIS              254
#define IDB_TB_OBJPROP_HOT              255
#define IDB_TB_SETTINGS                 256
#define IDB_TB_SETTINGS_DIS             257
#define IDB_TB_SETTINGS_HOT             258
#define IDB_TB_RUN                      259
#define IDB_TB_RUN_DIS                  260
#define IDB_TB_RUN_HOT                  261
#define IDB_TB_RUNCURR                  262
#define IDB_TB_RUNCURR_DIS              263
#define IDB_TB_RUNCURR_HOT              264
#define IDB_TB_HELP                     265
#define IDB_TB_HELP_DIS                 266
#define IDB_TB_HELP_HOT                 267
#define IDD_PROP_CUSTOMPARAM            268
#define IDD_PROP_NULL                   269
#define IDB_CUST_PARAM_STATIC           269
#define IDB_TB_SCRIPTS                  270
#define IDB_TB_SCRIPTS_DIS              271
#define IDB_TB_SCRIPTS_HOT              272
#define IDB_TB_BINDS                    273
#define IDB_TB_BINDS_DIS                274
#define IDB_TB_BINDS_HOT                275
#define IDB_ATTACH                      276
#define IDR_MENU_FLOORS                 278
#define IDB_TB_FLOORS                   279
#define IDB_TB_FLOORS_DIS               280
#define IDB_TB_FLOORS_HOT               281
#define IDB_TB_LOGS                     282
#define IDB_TB_LOGS_DIS                 283
#define IDB_LOGS_HOT                    284
#define IDB_TB_LOGS_HOT                 285
#define IDB_TB_TEXT_RESOURCES           286
#define IDB_TB_TEXT_RESOURCES_HOT       287
#define IDB_TB_TEXT_RESOURCES_DIS       288
#define IDD_DIALOG3                     289
#define IDD_TEXT_RESOURCES              289
#define IDB_HDRDOWN                     290
#define IDB_HDRUP                       291
#define IDR_ACCELERATOR_TEXT_RES_DLG    292
#define IDB_TEXT_RESOURCE               293
#define IDB_CUST_PARAM_DIS              294
#define IDD_ENGINE_MESSAGING            295
#define IDR_ACCELERATOR_ENGINE_MSG      296
#define IDD_PROP_CAMERA                 296
#define IDB_TB_ENGINE_CONSOLE           297
#define IDD_PROP_LIGHT                  297
#define IDR_MENU_XSI_CONTEXT            298
#define IDR_MENU_CONTEXT_XSI            298
#define IDR_MENU_EFN_CONTEXT            299
#define IDR_MENU_CONTEXT_EFN            299
#define IDR_MENU_MSH_CONTEXT            300
#define IDR_MENU_CONTEXT_MSH            300
#define IDB_VIEW_MENU                   301
#define IDR_MENU_VIEW                   302
#define IDR_MENU1                       303
#define IDR_MENU_SCN_CONTEXT            303
#define IDR_MENU_CONTEXT_SCN            303
#define IDB_TB_RELOAD_SCENE             305
#define IDB_TB_RELOAD_MESHES            306
#define IDD_DIALOG4                     307
#define IDD_DIALOG5                     308
#define IDB_TB_STOP                     310
#define IDB_TB_STOP_DIS                 311
#define IDB_TB_STOP_HOT                 312
#define IDD_BINKINFO                    313
#define IDD_OPENFILE_EXT                314
#define IDD_BATCH_CONVERT               316
#define IDD_CROP_FRAMES_TOOL            319
#define IDB_FUNCTION                    320
#define IDB_BITMAP1                     321
#define IDB_CLASS                       321
#define IDD_ANIMATION_DEGRADE_TOOL      322
#define IDD_CREATE_MESH_TESS            323
#define IDR_DEFAULT1                    324
#define IDR_DEFAULT2                    325
#define IDR_111                         326
#define IDB_ANIM_CTRLS_STOP             327
#define IDB_ANIM_CTRLS_PLAY             328
#define IDB_BITMAP2                     329
#define IDB_ANIM_CTRLS_ZOFFSET          329
#define IDB_ANIM_CTRLS_PAUSE            330
#define IDC_SCENE_TREE                  1001
#define IDC_PROGRESS                    1003
#define IDC_MESSAGE                     1004
#define IDC_RENDERWND                   1005
#define IDC_MESSAGE_PROGRESS            1005
#define IDC_CONT_FRAME                  1006
#define IDC_MESSAGE_PROGRESS2           1006
#define IDC_MESSAGE_PROGRESS3           1007
#define IDC_SPLITTER                    1008
#define IDC_MESSAGE_PROGRESS4           1008
#define IDC_ANIM_SLIDER                 1018
#define IDC_BTN_ANIM_PLAY               1021
#define IDC_CHK_LOOP_ANIM               1022
#define IDC_BTN_ANIM_STOP               1023
#define IDC_CURR_FRM                    1024
#define IDC_CURR_Z_OFF                  1028
#define IDC_BUTN_SET_Z_OFF              1029
#define IDC_EDIT                        1030
#define IDC_BUTTON1                     1031
#define IDC_BTN_CREATE_HANDLER          1031
#define IDC_SEND                        1031
#define IDC_BTN_MODELS                  1031
#define IDC_ANIMATION_NAME              1032
#define IDC_BTN_AMBLIGHT_COL            1032
#define IDC_BTN_LIGHT_AMBIENT_COL       1032
#define IDC_BTN_FILEOPEN                1032
#define IDC_BTN_REMOVE                  1032
#define IDC_BUTTON2                     1032
#define IDC_BTN_REPLACE_ALL             1032
#define IDC_BTN_CREATE_FUNCTION         1032
#define IDC_BTN_DEL                     1032
#define IDC_BTN_AMB                     1032
#define IDC_BTN_SCENES                  1032
#define IDC_ANIMATION_START             1033
#define IDC_BTN_GRIDWIRE_COL            1033
#define IDC_BTN_RIGHT_CLICK             1033
#define IDC_BTN_REMOVE_ALL              1033
#define IDC_BTN_SHOWALL                 1033
#define IDC_BTN_CREATE_SET              1033
#define IDC_BTN_A                       1033
#define IDC_ANIMATION_END               1034
#define IDC_BTN_GRIDCROSS_COL           1034
#define IDC_BTN_ALL_EVENTS              1034
#define IDC_BTN_HIDEALL                 1034
#define IDC_BTN_SEARCH                  1034
#define IDC_BTN_B                       1034
#define IDC_BTN_OK                      1035
#define IDC_BTN_ISECT_PORTAL            1035
#define IDC_BTN_RUNGAME                 1035
#define IDC_BTN_SEARCH_AND_REPLACE      1035
#define IDC_BTN_CANCEL                  1036
#define IDC_BTN_LIGHT_DIFFUSE_COL       1036
#define IDC_BTN_UPDATE_UI               1036
#define IDC_BTN_RUNGAME_CURR            1036
#define IDC_BTN_DIFF                    1036
#define IDC_BTN_AMBLIGHT_COL2           1037
#define IDC_BTN_SPEC                    1037
#define IDC_CHK_MOVE_CHAR               1038
#define IDC_EDIT_NEW_HEIGHT             1041
#define IDC_EDIT_CURR_HEIGHT            1042
#define ID_BTN_OK                       1043
#define ID_BTN_CANCEL                   1044
#define IDC_BTN_CLOSE                   1048
#define IDC_BTN_PREVIEW                 1049
#define IDC_CHECK2                      1050
#define IDC_CHECK3                      1051
#define IDC_COMBO1                      1052
#define IDC_COMBO2                      1053
#define IDC_CHECK4                      1054
#define IDC_CHK_ATTACH_LIGHT_TOCAMERA   1054
#define IDC_CMB_CHILD_ID                1054
#define IDC_COMBO3                      1054
#define IDC_CHECK5                      1055
#define IDC_CHK_SHOW_GRID               1055
#define IDC_CMB_CHILD_TYPE              1055
#define IDC_COMBO4                      1055
#define IDC_EDIT1                       1056
#define IDC_EDIT_GRID_SIZE              1056
#define IDC_EDIT_PAR1                   1056
#define IDC_EDIT_ALPHA                  1056
#define IDC_EDIT_POS_X                  1056
#define IDC_EDIT_FIND                   1056
#define IDC_EDIT_TRSCALE_X              1056
#define IDC_SCALE_X                     1056
#define IDC_TEXT                        1056
#define IDC_EDIT2                       1057
#define IDC_EDIT_GRID_CELLSIZE          1057
#define IDC_EDIT_EMM_ALPHA              1057
#define IDC_EDIT_POS_Y                  1057
#define IDC_EDIT_OBJECT_ID              1057
#define IDC_EDIT_REPLACE                1057
#define IDC_EDIT_TRSCALE_Y              1057
#define IDC_EDIT_VALUE                  1057
#define IDC_SCALE_Y                     1057
#define IDC_HISTORY                     1057
#define IDC_COMBO5                      1057
#define IDC_EDIT_HEIGHT                 1057
#define IDC_EDIT_TESSELATION_U          1057
#define IDC_SPIN1                       1058
#define IDC_SPIN_GRID_SIZE              1058
#define IDC_EDIT3                       1058
#define IDC_EDIT_HELP                   1058
#define IDC_EDIT_DIFF_ALPHA             1058
#define IDC_EDIT_POS_Z                  1058
#define IDC_EDIT_TRROT_X                1058
#define IDC_DIR_X                       1058
#define IDC_COMBO6                      1058
#define IDC_EDIT_RES_WIDTH              1058
#define IDC_EDIT_TESSELATION_V          1058
#define IDC_SPIN2                       1059
#define IDC_SPIN_CELL_SIZE              1059
#define IDC_EDIT4                       1059
#define IDC_EDIT_SPEC_ALPHA             1059
#define IDC_EDIT_ROT_X                  1059
#define IDC_EDIT_TRSCALE_Z              1059
#define IDC_DIR_Y                       1059
#define IDC_COMBO7                      1059
#define IDC_EDIT_RES_HEIGHT             1059
#define IDC_EDIT_SIZE_X                 1059
#define IDC_ED_DEF_FILES_DIR            1060
#define IDC_EDIT5                       1060
#define IDC_EDIT_POWER                  1060
#define IDC_EDIT_ROT_Y                  1060
#define IDC_EDIT_TRROT_Y                1060
#define IDC_SCALE_Z                     1060
#define IDC_COMBO8                      1060
#define IDC_EDIT_SIZE_Y                 1060
#define IDC_BUTTON5                     1061
#define IDC_BTN_BRWS_PATH               1061
#define IDC_EDIT6                       1061
#define IDC_BTN_EDIT                    1061
#define IDC_EDIT_ROT_Z                  1061
#define IDC_EDIT_TRROT_Z                1061
#define IDC_ROT_X                       1061
#define IDC_DIR_Z                       1061
#define IDC_COMBO9                      1061
#define IDC_EDIT_TESSELATION_BASE       1061
#define IDC_CMB_DEF_FILETYPE            1062
#define IDC_EDIT_SCALE_X                1062
#define IDC_BTN_UP                      1062
#define IDC_EDIT_TRTRANS_X              1062
#define IDC_ROT_Y                       1062
#define IDC_UPVEC_X                     1062
#define IDC_COMBO10                     1062
#define IDC_EDIT_SIZE_Z                 1062
#define IDC_BTN_VIEWPORTBACK_COL        1063
#define IDC_CHK_DIS_LIGHTING            1063
#define IDC_EDIT_SCALE_Y                1063
#define IDC_BTN_DOWN                    1063
#define IDC_EDIT_TRTRANS_Y              1063
#define IDC_ROT_Z                       1063
#define IDC_UPVEC_Y                     1063
#define IDC_COMBO11                     1063
#define IDC_BTN_VIEWPORTBACK_COL2       1064
#define IDC_BTN_VIEW_BACKCOLOR          1064
#define IDC_EDIT_SCALE_Z                1064
#define IDC_EDIT_TRTRANS_Z              1064
#define IDC_TRANS_X                     1064
#define IDC_UPVEC_Z                     1064
#define IDC_COMBO12                     1064
#define IDC_EDIT_ICON_SIZE              1065
#define IDC_EDIT_OBJ_ID                 1065
#define IDC_TRANS_Y                     1065
#define IDC_FOV_V                       1065
#define IDC_COMBO13                     1065
#define IDC_EDIT_RES_PIXCOUNT           1065
#define IDC_EDIT_ENGINE_EXEC            1066
#define IDC_TRANS_Z                     1066
#define IDC_FOV_H                       1066
#define IDC_EDIT_FRAMERATE              1066
#define IDC_CHECK1                      1067
#define IDC_CHK_RESET_CAMERA_ON_FILEOPEN 1067
#define IDC_CHK_PAR1                    1067
#define IDC_CHK_TRANSITION              1067
#define IDC_CHK_CASE                    1067
#define IDC_CHK_AMB_DIFF                1067
#define IDC_CHK_ZOOM_NEAR               1067
#define IDC_EDIT_FRAMESCOUNT            1067
#define IDC_CHECK_LOCK_SIZE             1067
#define IDC_CHECK6                      1068
#define IDC_VERSION                     1068
#define IDC_CHK_CAMERA_TO_CURRENT       1068
#define IDC_CHK_CURR_BIND               1068
#define IDC_ZOOM_NEAR                   1068
#define IDC_CHK_AMB_DIFF2               1068
#define IDC_EDIT_ALPHA_PRESENT          1068
#define IDC_CHK_REPLACE_EXISTING        1068
#define IDC_CHECK_LOCK_TESSELATION      1068
#define IDC_BUILD                       1069
#define IDC_CHK_CLEAR_RECENT_FILES_LIST 1069
#define IDC_CHECK7                      1069
#define IDC_ZOOM_FAR                    1069
#define IDC_RANGE                       1069
#define IDC_CHK_AMB_DIFF3               1069
#define IDC_CHK_NORMALS                 1069
#define IDC_CHECK8                      1070
#define IDC_CHK_DONT_REPAIR_XSI         1070
#define IDC_CLIP_NEAR                   1070
#define IDC_THETA                       1070
#define IDC_CHK_AMB_DIFF4               1070
#define IDC_CHK_ANIM_RANGE              1070
#define IDC_CHECK9                      1071
#define IDC_CHK_BINDS_FILTER_OBJS_BYPREFX 1071
#define IDC_CLIP_FAR                    1071
#define IDC_MULTIPLIER                  1071
#define IDC_CHK_AMB_DIFF5               1071
#define IDC_CHK_MATERIAL_TO_DEFAULTS    1071
#define IDC_CHECK10                     1072
#define IDC_CHK_SCN_FILES_ALT_NULL_ICO  1072
#define IDC_CHK_ZOOM_FAR                1072
#define IDC_CHK_ZOOM_NEAR2              1072
#define IDC_CHK_MATERIAL_TO_DEFAULTS2   1072
#define IDC_CHK_SHULTZ_SCALING          1072
#define IDC_BTN_BRWS_ENGINE_PATH        1073
#define IDC_PHI                         1073
#define IDC_CHK_MATERIAL_TO_DEFAULTS3   1073
#define IDC_CLIP_NEAR2                  1073
#define IDC_CHK_BINDS_SHOW_CUST_OBJS    1074
#define IDC_CHK_ZOOM_NEAR3              1074
#define IDC_CLIP_FAR2                   1074
#define IDC_CHK_ASK_FOR_FILE_SAVING     1075
#define IDC_CLIP_FAR3                   1075
#define IDC_CHK_BACKFACE_CULL           1076
#define IDC_BTN_FILESAVE                1077
#define IDC_CHK_PRESERVE4_3             1077
#define IDC_CMB_CAMERAS                 1078
#define IDC_CHK_BINDS_SHOW_CUST_OBJS2   1078
#define IDC_CHK_1ST_MONITOR             1078
#define IDC_FRM_TOOLBAR_TOP             1079
#define IDC_EDIT_ENGINE_DIR             1079
#define IDC_FRM_TOOLBAR_BOTTOM          1080
#define IDC_BTN_BRWS_ENGINE_DIR         1080
#define IDC_BTN_FILESAVE_AS             1081
#define IDC_CMB_VIEWS                   1081
#define IDC_EDIT_CUSTBTN_CAPTION_A      1081
#define IDC_EDIT_DEST_DIR               1081
#define IDC_LIST_BINDS                  1082
#define IDC_BTN_FILESAVE_ALL            1082
#define IDC_EDIT_CUSTBTN_PATH_A         1082
#define IDC_BTN_DEST_PATH_BRWS          1082
#define IDC_BTN_ADD                     1083
#define IDC_EDIT_CUSTBTN_PATHBRW_A      1083
#define IDC_CMB_PAR_ID                  1084
#define IDC_EDIT_CUSTBTN_CAPTION_B      1084
#define IDC_CMB_PAR_TYPE                1085
#define IDC_EDIT_CUSTBTN_PATH_B         1085
#define IDC_BTN_ADD_ANOTHER             1086
#define IDC_EDIT_CUSTBTN_PATHBRW_B      1086
#define IDC_EDIT_DEFAULT_CAM_FOV        1087
#define IDC_LST_LOG                     1088
#define IDC_CHK_RUN_ENGINE_DEBUG        1088
#define IDC_RICHEDIT21                  1089
#define IDC_RCH_SCRIPTSRC               1089
#define IDC_CHK_SWCH_ENGINE_DEBUG       1089
#define IDC_LST_CHILD_ID                1090
#define IDC_CMB_FILTER_PAR_TYPE         1091
#define IDC_CMB_FILTER_PAR_ID           1092
#define IDC_SCRIPT_TEXT                 1093
#define IDC_SLIDER                      1095
#define IDC_BTM_FRM_SCRIPT_SAVE         1096
#define IDC_LST_OBJECT                  1098
#define IDC_BTN_LEFT_CLICK              1099
#define IDC_BTN_TIMER                   1100
#define IDC_LIST1                       1101
#define IDC_BTN_SEQ_INIT                1101
#define IDC_LST_SRC_FILES               1101
#define IDC_LIST_RANGES                 1101
#define IDC_BTN_COLOR                   1102
#define IDC_BTN_SCN2SCN                 1102
#define IDC_LST_CHOSEN_DATA             1102
#define IDC_BTN_MAN_GO                  1103
#define IDC_LST_IMPORT_DATA             1103
#define IDC_BTN_EMM_COLOR               1103
#define IDC_BTN_ADD_ALL                 1104
#define IDC_BTN_DIFF_COLOR              1104
#define IDC_WARNING_MSG                 1105
#define IDC_BTN_SPEC_COLOR              1105
#define IDC_BTN_REPLACE                 1106
#define IDC_EDIT_AMB_ALPHA              1107
#define IDC_BTN_AMB_COLOR               1108
#define IDC_LST_FRAMES                  1109
#define IDC_PUSH_AXES_X                 1110
#define IDC_PUSH_AXES_Y                 1111
#define IDC_PUSH_AXES_Z                 1112
#define IDC_TREE1                       1112
#define IDC_PUSH_AXES_XY                1113
#define IDC_CMB_PARENT_TYPE             1113
#define IDC_PUSH_AXES_XZ                1114
#define IDC_CMB_PARENT_ID               1114
#define IDC_PUSH_AXES_YZ                1115
#define IDC_CMB_HANDLERS_COMBO          1115
#define IDC_CMB_FUNCTIONS               1116
#define IDC_TRANSFORM_FRAME             1116
#define IDC_CMB_PREDEFINED_SETS         1117
#define IDC_IMG_TR_SCALE                1117
#define IDC_TRANSFORM_FRAME3            1117
#define IDC_IMG_TR_ROTT                 1118
#define IDC_TRANSFORM_FRAME2            1118
#define IDC_CMB_FILTER_TYPE             1118
#define IDC_IMG_TR_TRANS                1119
#define IDC_TRANSFORM_FRAME4            1119
#define IDC_CMB_FILTER_ID               1119
#define stc32                           0x045f
#define IDC_LBL_TRSCALE_X               1120
#define IDC_TRANSFORM_FRAME8            1120
#define IDC_LBL_TRSCALE_Y               1121
#define IDC_LBL_TRSCALE_Z               1122
#define IDC_LBL_TRROT_X                 1123
#define IDC_LBL_TRSCALE_X2              1123
#define IDC_LBL_TRROT_Y                 1124
#define IDC_LBL_TRSCALE_Y2              1124
#define IDC_LBL_TRROT_Z                 1125
#define IDC_LBL_TRSCALE_Z2              1125
#define IDC_LBL_TRTRANS_X               1126
#define IDC_LBL_TRSCALE_X3              1126
#define IDC_LBL_TRTRANS_Y               1127
#define IDC_LBL_TRSCALE_Y3              1127
#define IDC_LBL_TRTRANS_Z               1128
#define IDC_LBL_TRSCALE_Z3              1128
#define IDC_STATIC_LINENUM              1129
#define IDC_LBL_TRSCALE_X4              1129
#define IDC_CAM_CMB_LBL                 1130
#define IDC_LBL_TRSCALE_Y4              1130
#define IDC_OBJPROP_WND_FRAME           1131
#define IDC_TRANSFORM_FRAME5            1131
#define IDC_EDIT_ID                     1132
#define IDC_CAM_CMB_LBL2                1132
#define IDC_VIEW_CMB_LBL                1132
#define IDC_LEXER_FRM                   1133
#define IDC_LBL_TRSCALE_X5              1133
#define IDC_TRANSFORM_FRAME6            1133
#define IDC_OUTPUT_FRM                  1134
#define IDC_TRANSFORM_FRAME7            1134
#define IDC_EDIT_TYPE                   1135
#define IDC_TRANSFORM_FRAME11           1135
#define IDC_SLIDERH                     1136
#define IDC_LBL_TRSCALE_Y5              1136
#define IDC_TRANSFORM_FRAME9            1136
#define IDC_OUT_HDR                     1137
#define IDC_LBL_TRSCALE_X6              1137
#define IDC_TRANSFORM_FRAME10           1137
#define IDC_OUT_HDR_LBL                 1138
#define IDC_LBL_TRSCALE_Y6              1138
#define IDC_LBL_TRSCALE_X7              1139
#define IDC_BMP                         1140
#define IDC_LBL_TRSCALE_Y7              1140
#define IDC_POS_X                       1141
#define IDC_POS_Y                       1142
#define IDC_POS_Z                       1143
#define IDC_ATTENUATION                 1144
#define IDC_LBL_TRSCALE_X8              1144
#define IDC_CHK_RANGE                   1145
#define IDC_LBL_TRSCALE_Y8              1145
#define IDC_SPIN_MULT                   1146
#define IDC_LBL_TRSCALE_Y9              1146
#define IDC_SPIN_ATTEN                  1147
#define IDC_FILTER_FRM                  1147
#define IDC_SPIN3                       1149
#define IDC_TAB1                        1151
#define IDC_EDIT_WIDTH                  1152
#define IDC_LST_OBJECT_                 1155
#define IDC_TREE_OBJECTS                1156
#define IDC_BTN_SRC_PATH_BRWS           1158
#define IDC_EDIT_MAX                    1162
#define IDC_EDIT_MIN                    1163
#define IDC_COMBOBOXEX_FUNCS            1165
#define IDC_COMBOBOXEX_CLASSES          1166
#define IDC_EDIT_PERCENTAGE             1166
#define IDC_SLIDER_TESSELATION_U        1167
#define IDC_SLIDER_TESSELATION_V        1168
#define IDC_SLIDER_SIZE_X               1169
#define IDC_SLIDER_SIZE_Y               1170
#define IDC_SLIDER_SIZE_Z               1171
#define IDC_SLIDER_TESSELATION_BASE     1172
#define IDC_STATIC_SIZE_X               1173
#define IDC_STATIC_SIZE_Y               1174
#define IDC_STATIC_SIZE_Z               1175
#define IDC_STATIC_TESS_U               1176
#define IDC_STATIC_TESS_V               1177
#define IDC_STATIC_TESS_BASE            1178
#define IDC_CHK_LOOP_TRANSITION         1179
#define IDC_TREE_PARENT_ID              1180
#define ID_FILE_EXIT                    32772
#define ID_MY_BAR                       32772
#define ID_SHOWMESH                     32776
#define ID_HIDEMESH                     32777
#define ID_MENU_SERTG                   32778
#define ID_SG_SDFG                      32779
#define ID_MENU_ABOUT                   32780
#define ID_MENU_SHOWMESHES              32784
#define ID_MENU_HIDEMESHES              32785
#define ID_32786                        32786
#define ID_T_WIREFRAME                  32787
#define ID_T_SHADED                     32788
#define ID_Menu                         32789
#define ID_MENU_BACKFACE_CULLING        32792
#define ID_MENU_BACKCOLOR               32793
#define ID_MEM_ALLOCATE                 32800
#define ID_MENU_SAVE_AS                 32802
#define ID_CREATE_SEQUENCE              32804
#define ID_ILDAR_WINDOW                 32806
#define ID_MENU_EDIT_MODEl_NAME         32808
#define ID_MENU_EDIT_MODEL_NAME         32809
#define ID_L_                           32810
#define ID_MENU_SAVE                    32812
#define ID_MENU_DISCARD_VERT_COL        32814
#define ID_MENU_ADD_ANIM                32816
#define ID_MENU4_                       32818
#define ID_MENU5                        32819
#define ID_MENU_DEL_ALL_ANIM            32820
#define ID_MENU_DEL_ANIM_ITEM           32823
#define ID_MENU_EDIT_ANIM_ITEM          32824
#define ID_MENU_RUN_ANIM_ITEM           32826
#define ID_MENU_PLAY_SEQUENCE           32830
#define ID_Menu32833                    32833
#define ID_MENU_AA_NONE                 32837
#define ID_MENU_AA_X2                   32838
#define ID_MENU_AA_X4                   32839
#define ID_MENU_AA_X6                   32840
#define ID_MENU_CONV_COORDS_SYS         32844
#define ID_MENU_SCALE                   32846
#define ID_T_WIREFRAME_SHADED           32848
#define ID_32849                        32849
#define ID_MENU_SWAPYZ                  32852
#define ID_MENU_OPTIONS                 32853
#define ID_CLOSE                        32854
#define ID_MENU_MESH_INVERSE_NORMALS    32856
#define ID_Menu32857                    32857
#define ID_MENU_LIGHT_PROP              32859
#define ID_MENU_SET_CAMERA_TOCURRENT    32861
#define ID_MENU_RETURN_TO_PERSPECTIVEVIEW 32863
#define ID_32868                        32868
#define ID_MENU_SHOW_AABB               32870
#define ID_MENU_SHOW_BSPHERE            32871
#define ID_MENU_TEST_WALK               32872
#define ID_MENU_RECALC_GLOBAL_RADIUS    32874
#define ID_MENU_CONV_TO_EFN_MESHLIST    32876
#define ID_MENU_CONV_TO_EFN_ANIM        32877
#define ID_MENU_CONV_TO_SCN             32878
#define ID_MENU_GENERATEOUTPUT          32880
#define ID_TEMP_GENERATEGRID            32881
#define ID_MENU_TESTLOADGRID            32883
#define ID_MENU_SHOW_ALL_CAMS           32890
#define ID_MENU_HIDE_ALL_CAMS           32891
#define ID_MENU_SHOW_ALL_LIGHT          32892
#define ID_MENU_HIDE_ALL_LIGHT          32893
#define ID_MENU_TESTLOADSCENE           32895
#define ID_RENDER_SHADING               32896
#define ID_SHADING_TEXTURED             32897
#define ID_RENDER_CAMERAS               32898
#define ID_CAMERAS_PERSPECTIVE          32899
#define ID_Menu32900                    32900
#define ID_ACCL_SWITCH_2_PERSPECTIVE_CAM 32902
#define ID_ACCL_FILE_OPEN               32904
#define ID_ACCL_SELECT_ALL_ANIM_FRAMES  32906
#define ID_ACCL_SELECT_ALL_OBJECTS      32906
#define ID_ACCL_DESELECT_ALL_ANIM_FRAMES 32908
#define ID_ACCL_DESELECT_ALL_OBJECTS    32908
#define ID_ACCL_DELETE_SELECTED_AMIN_FRAMES 32909
#define ID_ACCL_DELETE_SELECTED_OBJECTS 32909
#define ID_Menu32911                    32911
#define ID_Menu32912                    32912
#define ID_L_G                          32913
#define ID_Menu32914                    32914
#define ID_L_RECENTFILES                32915
#define ID_Menu32916                    32916
#define ID_Menu32917                    32917
#define ID_RECENTFILES_RTY              32918
#define ID_RECENTFILES_56               32919
#define ID_MENU_MESHLIST_MESHES_HIDE    32928
#define ID_MENU_MESHLIST_MESHES_SHOW    32929
#define ID_MENU_MESHLIST_MESH_SHOW      32930
#define ID_MENU_MESHLIST_MESH_HIDE      32931
#define ID_MENU_MESHLIST_MESH_RENAME    32933
#define ID_MENU_MESHLIST_MESH_DELETE    32934
#define ID_MENU_FPS_CHANGE              32943
#define ID_MENU_LOAD_TEXTURE            32945
#define ID_MENU_MESHLIST_SCENETAG       32948
#define ID_MENU_MESHLIST_MESH_SCRIPT    32950
#define ID_MENU_TEXTURE_REMOVE_ALL      32954
#define ID_Menu32955                    32955
#define ID_MENU_FLOOR_RECALC            32956
#define ID_MENU_FLOOR_SHOWONLY          32958
#define ID_MENU_FLOOR_SHOW_GRID         32960
#define ID_MENU_FLOOR_SHOW_SELECTOR     32962
#define ID_MENU_FLOOR_SELECTOR_SHOWONLY 32964
#define ID_MESHLIST_NULL_ATTACH         32967
#define ID_MESHLIST_NULL_DETACH         32968
#define ID_ACCL_SAVE                    32969
#define ID_ACCL_OPEN_SCRIPTS_DLG        32971
#define ID_MENU_SCENE_CAMS_OBJECT_BIND  32978
#define ID_MENU_SCENE_CAMS_OBJECT_SCRIPT 32979
#define ID_MENU_SCENE_CAMS_OBJECT_DELETE 32980
#define ID_MENU_SCN_MESHES_SHOW         32983
#define ID_MENU_SCN_MESHES_HIDE         32984
#define ID_MENU_SCN_MESH_SHOW           32987
#define ID_MENU_SCN_MESH_HIDE           32988
#define ID_MENU_SCN_CAMERAS_SHOW        32991
#define ID_MENU_SCN_CAMERAS_HIDE        32992
#define ID_MENU_SCN_CAMERA_SHOW         32996
#define ID_MENU_SCN_CAMERA_HIDE         32997
#define ID_MENU_SCN_CAMERA_OBJECTS      32998
#define ID_MENU_SCN_LIGHTS_SHOW         33001
#define ID_MENU_SCN_LIGHTS_HIDE         33002
#define ID_MENU_SCN_LIGHT_SHOW          33005
#define ID_MENU_SCN_LIGHT_HIDE          33006
#define ID_ACCL_WIRE                    33007
#define ID_ACCL_FLAT                    33008
#define ID_ACCL_FLAT_AND_WIRE           33009
#define ID_ACCL_ADD_ANOTHER_BIND        33011
#define ID_ACCL_SWITCH_CULLING          33012
#define ID_ACCL_OPEN_BINDS_DLG          33014
#define ID_MENU_SCN_CAM_ZOOMNEAR        33018
#define ID_MENU_SCN_CAM_ZOOMFAR         33019
#define ID_ACCL_HELP                    33020
#define ID_ACCL_OPTIONS                 33022
#define ID_MENU_SCN_LIGHT_DIFFUSE       33025
#define ID_MENU_SCN_LIGHT_AMB           33027
#define ID_MENU_SCN_MESH_VCOL           33029
#define ID_MENU_SCN_LIGHT_RANGE         33033
#define ID_MENU_SCN_LIGHT_ATTENUATION   33034
#define ID_MENU_SCN_LIGHT_MULTIPLIER    33035
#define ID_MENU_SCN_CUST_OBJ_ADDNEW     33040
#define ID_MENU_SCN_CUST_OBJ_DELALL     33041
#define ID_MENU_SCN_CUST_TYPE_DELALL    33042
#define ID_MENU_SCN_CUST_TYPE_ADDNEW    33043
#define ID_MENU_SCN_CUST_TYPE_DEL       33046
#define ID_MENU_SCN_CUST_OBJ_DEL        33047
#define ID_MENU_SCN_BINDS_SHOW_WND      33050
#define ID_MENU_SCN_SCRIPTS_SHOW_WND    33052
#define ID_MENU_FLOOR_UV_RECALC         33054
#define ID_L_RECENTFOLDERS              33055
#define ID_Menu33056                    33056
#define ID_MENU_SCN_BACK_ADD            33058
#define ID_MENU_SCN_TEXTURE_ADD         33059
#define ID_MENU_SCN_TEXTURE_DEL         33061
#define ID_MENU_SCN_NULL_EDIT_POS_X     33066
#define ID_MENU_SCN_NULL_EDIT_POS_Y     33067
#define ID_MENU_SCN_NULL_EDIT_POS_Z     33068
#define ID_MENU_SCN_NULL_EDIT_ROT_Y     33070
#define ID_MENU_SCN_NULL_EDIT_ROT_X     33073
#define ID_MENU_SCN_NULL_EDIT_ROT_Z     33074
#define ID_MENU_IMPORT                  33076
#define ID_ACCL_RUN_ENGINE              33078
#define ID_EFN_EDIT_MATERIAL            33083
#define ID_EFN                          33084
#define ID_EFN_NULL_EDIT_MATERIAL       33087
#define ID_EFN_NULL_LOAD_TEXTURE        33089
#define ID_EFN_ANIM_SCRIPTS_EDITOR      33091
#define ID_EFN_NULLS_DETACH_ALL         33093
#define ID_MENU_EFN_NULL_SCALING        33096
#define ID_EFN_MESHLIST_NULL_RENAME     33106
#define ID_EFN_MESHLIST_NULL_REMOVE     33107
#define ID_EFN_MESHLIST_NULL_ROTATION   33109
#define ID_EFN_MESHLIST_NULL_ATTACH     33110
#define ID_EFN_MESHLIST_NULL_DETACH     33111
#define ID_EFN_MESHLIST_NULL_POSITION_ROTATION 33112
#define ID_EFN_MESHLIST_NULLS_NEW       33113
#define ID_EFN_MESHLIST_NULLS_REMOVE_ALL 33114
#define ID_EFN_MESHLIST_NULLS_DETACH_ALL 33115
#define ID_ACCL_HIDE_SELECTED           33116
#define ID_ACCL_UNHIDE_ALL              33117
#define ID_ACCL_SWITCH_EDITING_MESH_VERTICES 33118
#define ID_MENU_MESHLIST_MESH_EDIT_VERTICES 33120
#define ID_MENU_EFN_NULL_ATTACH         33122
#define ID_MENU_EFN_NULL_DETACH         33123
#define ID_MENU_MESHLIST_MESH_SHOW_ONLY 33125
#define ID_ACCL_SHOW_ONLY               33126
#define ID_MESHLIST_NULL_HIDE           33130
#define ID_MESHLIST_NULL_SHOW           33131
#define ID_ACCL_SHOW_BBOX               33132
#define ID_ACCL_SHOW_BSPH               33133
#define ID_ACCL_AXES_X                  33135
#define ID_ACCL_AXES_Y                  33136
#define ID_ACCL_AXES_Z                  33137
#define ID_ACCL_AXES_XY                 33138
#define ID_ACCL_AXES_XZ                 33139
#define ID_ACCL_AXES_YZ                 33140
#define ID_MENU_MESHLIST_MESH_MATERIAL  33143
#define ID_ACCL_ESCAPE                  33144
#define ID_MENU_SCN_MESH_SHOWONLY       33147
#define ID_MENU_SCN_CAMERA_SHOW_ONLY    33149
#define ID_SCNLIGHT_ONMENUSCNCAMERASHOWONLY 33151
#define ID_MENU_SCN_LIGHT_SHOW_ONLY     33153
#define ID_MENU_SCN_MESH_EDIT_MATERIAL  33155
#define ID_ACCL_MATERIAL                33156
#define ID_MENU_SCN_MESH_EDIT_VERTECIES 33159
#define ID_MENU_SCN_NULLS_SHOW          33162
#define ID_MENU_SCN_NULLS_HIDE          33163
#define ID_SCNNULL                      33166
#define ID_MENU_SCN_NULL_POS_ROT_SCALE  33170
#define ID_MENU_SCN_NULL_ATTACH         33171
#define ID_MENU_SCN_NULL_DETACH         33172
#define ID_MENU_SCN_NULLS_CREATE_NEW    33173
#define ID_MENU_SCN_NULLS_DETACH_ALL    33175
#define ID_MENU_EFN_NULL_RENAME         33179
#define ID_ACCL_MAXIMIZE                33180
#define ID_MENU_FILE_ASSOCIATIONS       33183
#define ID_MENU_MESHLIST_MESH_DUPLICATE 33185
#define ID_MESHLISTMESHES_33186         33186
#define ID_MENU_MESHLIST_MESHES_CREATE_CUBE 33190
#define ID_MENU_MESHLIST_MESHES_CREATE_POLY 33191
#define ID_MENU_MESHLIST_MESHES_CREATE_QUAD 33192
#define ID_SCNMESH_33195                33195
#define ID_33197                        33197
#define ID_33198                        33198
#define ID_MENU_SCN_MESH_DELETE         33199
#define ID_MENU_SCN_MESH_RENAME         33200
#define ID_SCNMESHES_33201              33201
#define ID_Menu33205                    33205
#define ID_MENU_SCN_MESH_DUPLICATE      33207
#define ID_MENU_SCN_MESHES_CREATE_BOX   33208
#define ID_MENU_SCN_MESHES_CREATE_TRIANGLE 33209
#define ID_MENU_SCN_MESHES_CREATE_QUAD  33210
#define ID_MENU_SCN_NULL_RENAME         33213
#define ID_MENU_SCN_NULL_DELETE         33214
#define ID_MENU_SCN_TEXTURE_BIND_2_CAM  33216
#define ID_MENU_SCN_MESH_BIND_2_TEXTURE 33220
#define ID_MENU_SCN_LIGHTS_BIND_2_CAMERA 33222
#define ID_MENU_START_MACRO_REC         33227
#define ID_MENU_END_MACRO_REC           33228
#define ID_MENU_LOAD_MACRO              33229
#define ID_MENU_SCN_CAMERA_SCRIPT       33231
#define ID_MENU_SCN_LIGHT_SCRIPT        33233
#define ID_MENU_SCN_TEXTURE_SCRIPT      33235
#define ID_ACCL_ENGINE                  33236
#define ID_ACCL_FIND                    33238
#define ID_ACCL_REPLACE                 33239
#define ID_ACCL_FIND_NEXT               33240
#define ID_ACCL_RUN_ENGINE_CURR         33242
#define ID_ACCL_ENGINE_CURR             33244
#define ID_MENU_SCALE_NEW               33247
#define ID_EFN_NULLS_RESCALE_ALL        33249
#define ID_MENU_OBJ_PROPERTIES_WND      33251
#define ID_ACCL_SHOW_OBJ_PROP_WND       33252
#define ID_ACCL_SHOW_GRID               33254
#define ID_MENU_FILE_OPEN               33256
#define ID_MENU_AXIS_X                  33263
#define ID_MENU_AXIS_Y                  33264
#define ID_MENU_AXIS_Z                  33265
#define ID_MENU_AXIS_XY                 33266
#define ID_MENU_AXIS_XZ                 33267
#define ID_MENU_AXIS_YZ                 33268
#define ID_MENU_XSI_MESH_DISCONNECT_TRIS 33269
#define ID_MENU_XSI_MESH_CONNECT_TRIS   33271
#define ID_Menu33272                    33272
#define ID_EFNMESH_DISCONNECTPOLYS      33273
#define ID_EFNMESH_CONNECTPOLYS         33274
#define ID_MENU_EFN_MESH_CONNECTPOLYS   33277
#define ID_MENU_EFN_MESH_DISCONNECTPOLYS 33278
#define ID_ACCL_PERSPECTIVE             33279
#define ID_ACCL_FRONT                   33280
#define ID_ACCL_TOP                     33281
#define ID_ACCL_RIGHT                   33282
#define ID_MENU_FLOOR_MATERIAL          33289
#define ID_Menu33292                    33292
#define ID_MENU_MESHLIST_MESH_INVERSE_NORMALS 33297
#define ID_MENU_MESHLIST_MESH_DISCONNECT_TRIS 33298
#define ID_MENU_MESHLIST_MESH_CONNECT_TRIS 33300
#define ID_MENU_SCN_MESH_INVERSE_NORMALS 33302
#define ID_MENU_SCN_MESH_CONNECT_TRIS   33304
#define ID_MENU_SCN_MESH_DISCONNECT_TRIS 33306
#define ID_EFN_MESHLIST_NULLS_SHOW_ALL  33309
#define ID_EFN_MESHLIST_NULLS_HIDE_ALL  33310
#define ID_MENU_MESHLIST_MERGE_SELECTED 33315
#define ID_MENU_MESHLIST_DELETE_SELECTED 33316
#define ID_MENU_MESHLIST_MESHES_DELETE_ALL 33317
#define ID_MENU_SEL_DELETE_OBJECTS      33320
#define ID_T_33322                      33322
#define ID_MENU_SEL_GEOM_MATERIAL       33329
#define ID_MENU_SEL_GEOM_MERGE          33330
#define ID_MENU_SEL_GEOM_DISCONNECT_TRIS 33332
#define ID_MENU_SEL_GEOM_FLIP_NORMALS   33333
#define ID_ACCL_COMMENT_BLOCK           33334
#define ID_ACCL_UNCOMMENT_BLOCK         33335
#define ID_DEVTOOLS_UPDATESCENES        33337
#define ID_ACCL_OPEN_TEXT_RES_DLG       33338
#define ID_ACCL_TEXT_RES                33346
#define ID_ACCL_SRIPTS_ED               33352
#define ID_Menu33354                    33354
#define ID_MENU_SCN_CAMERA_OBJ_SCRIPT   33358
#define ID_MENU_SCN_CAMERA_OBJ_BIND     33359
#define ID_MENU_SCN_CURVES_NEW          33365
#define ID_MENU_SCN_CURVE_ADDSELECTEDNULL 33367
#define ID_MENU_SCN_CURVES_SHOW_ALL     33368
#define ID_MENU_SCN_CURVES_HIDE_ALL     33369
#define ID_MENU_SCN_CURVES_DELETE_ALL   33370
#define ID_MENU_SCN_CURVE_REMOVE_ALL_NULLS 33375
#define ID_MENU_SCN_CURVE_DELETE        33376
#define ID_MENU_SCN_CURVE_RENAME        33377
#define ID_MENU_SCN_CURVE_SETTYPE       33378
#define ID_MENU_SCN_CURVE_TYPE_LINEAR   33381
#define ID_MENU_SCN_CURVE_TYPE_CATMUL   33382
#define ID_MENU_SCN_CURVE_NULL_REMOVE   33386
#define ID_MENU_SCN_CURVE_NULL_MOVEUP   33387
#define ID_MENU_SCN_CURVE_NULL_MOVEDOWN 33388
#define ID_ACCL_CURVE_NULL_UP           33390
#define ID_ACCL_CURVE_NULL_DOWN         33392
#define ID_MENU_ENGINE_MESSAGING        33395
#define ID_ACCL_ENGINE_MESSAGING        33396
#define ID_ACCL_SEND                    33398
#define ID_ACCL_PARSE_SCRIPTS           33400
#define ID_Menu33402                    33402
#define ID_MENU_SEL_INVERSE             33405
#define ID_MENU_SEL_HIDE                33406
#define ID_MENU_SELECT_VISIBLE          33408
#define ID_MENU_RENAME                  33411
#define ID_MENU_DUPLICATE               33412
#define ID_ACCL_RENAME                  33413
#define ID_MENU_SAVE_IN_RECENT_AS       33417
#define ID_EFN_NULLS_RELOAD_ATTACHES    33419
#define ID_ACCL_DEL                     33420
#define ID_Menu33433                    33433
#define ID_MENU_SCN_LIGHTS_DELETE       33439
#define ID_MENU_SCN_CAMERAS_DELETE      33441
#define ID_MENU_SCN_MESHES_DELETE       33443
#define ID_MENU_SCN_NULLS_DELETE        33445
#define ID_MENU_SCN_TEXTURE_RENAME      33447
#define ID_MENU_SCN_CUST_OBJ_RENAME     33450
#define ID_MENU_SCN_CUST_TYPE_RENAME    33451
#define ID_MENU_SCN_LIGHT_RENAME        33454
#define ID_MENU_SCN_CAMERA_RENAME       33455
#define ID_MENU_SCN_LIGHT_DELETE        33458
#define ID_MENU_SCN_CAMERA_DELETE       33459
#define ID_MENU_VIEW_GRID               33460
#define ID_MENU_VIEW_LIGHTS             33462
#define ID_MENU_VIEW_NULLS              33464
#define ID_MENU_VIEW_CURVES             33465
#define ID_MENU_VIEW_CHECKALLOBJECTS    33466
#define ID_MENU_VIEW_UNCHECKALLOBJECTS  33467
#define ID_MENU_VIEW_NORMALS            33468
#define ID_MENU_VIEW_BOUNDINGBOX        33469
#define ID_MENU_VIEW_BOUNDINGSPHERE     33470
#define ID_MENU_VIEW_SHADED             33471
#define ID_MENU_VIEW_WIREFRAME          33472
#define ID_MENU_VIEW_TEXTURED           33473
#define ID_MENU_VIEW_HIDDENLINEREMOVAL  33474
#define ID_MENU_VIEW_FRAMERATE          33475
#define ID_MENU_VIEW_CAMERAS            33477
#define ID_MENU_VIEW_SPOTLIGHTCONE      33479
#define ID_MENU_SCN_RESTORE_ENGINE_CAMS 33481
#define ID_MENU_VIEW_CAMERA_INTEREST    33483
#define ID_ACCL_CENTER_CAM_ON_OBJ       33484
#define ID_L_33486                      33486
#define ID_MENU_CREATE_SCENE            33489
#define ID_MENU_CREATE_MESHLIST         33490
#define ID_T_HIDEBYTYPE                 33491
#define ID_T_SHOWBYTYPE                 33492
#define ID_MENU_HIDEBYTYPE_CAMERAS      33503
#define ID_MENU_HIDEBYTYPE_LIGHTS       33504
#define ID_MENU_HIDEBYTYPE_MESHES       33505
#define ID_MENU_HIDEBYTYPE_NULLS        33506
#define ID_MENU_HIDEBYTYPE_CURVES       33507
#define ID_MENU_HIDEBYTYPE_LAYERGEOM    33509
#define ID_MENU_HIDEBYTYPE_CAMERASELECTORS 33510
#define ID_MENU_HIDEBYTYPE_ACTIONOBJECTS 33511
#define ID_MENU_HIDEBYTYPE_ALL          33512
#define ID_MENU_SHOWBYTYPE_CAMERAS      33513
#define ID_MENU_SHOWBYTYPE_LIGHTS       33514
#define ID_MENU_SHOWBYTYPE_MESHES       33515
#define ID_MENU_SHOWBYTYPE_NULLS        33516
#define ID_MENU_SHOWBYTYPE_CURVES       33517
#define ID_MENU_SHOWBYTYPE_FLOORS       33518
#define ID_MENU_HIDEBYTYPE_FLOORS       33519
#define ID_MENU_SHOWBYTYPE_CAMERASELECTORS 33521
#define ID_MENU_SHOWBYTYPE_ACTIONOBJECTS 33522
#define ID_MENU_SHOWBYTYPE_ALL          33523
#define ID_MENU_SHOWBYTYPE_LAYERGEOM    33524
#define ID_L_BATCHCONVERTATION          33525
#define ID_MENU_BATCHCONVERTATION_XSI2ANIMEFN 33527
#define ID_T_CREATEOBJECT               33528
#define ID_MENU_CREATEOBJECT_NULL       33533
#define ID_MENU_CREATEOBJECT_BOX        33534
#define ID_MENU_CREATEOBJECT_QUAD       33535
#define ID_MENU_CREATEOBJECT_TRIANGLE   33536
#define ID_CUSTOBJECT_33537             33537
#define ID_Menu33538                    33538
#define ID_MENU_SCN_CUST_OBJ_BIND_2_CAMERA 33540
#define ID_MENU_SCN_MESH_BIND_2_CAMERA  33541
#define ID_MENU_SEL_GEOM_ALIGN_POINTS   33543
#define ID_MENU_EFN_NULL_DETACH_ALL     33544
#define ID_MENU_UNLOAD_TEXTURE          33546
#define ID_MENU_CREATEOBJECT_NULL_ON_CURVE 33548
#define ID_TEXTURE_UVMAPS               33549
#define ID_MENU_EFN_USE_UV1             33552
#define ID_MENU_EFN_USE_UV2             33553
#define ID_ACCL_STOP_ENGINE             33554
#define ID_MENU_HIDEBYTYPE_OCCLUDERS    33556
#define ID_MENU_SHOWBYTYPE_OCCLUDERS    33559
#define ID_MENU_EFN_NULL_DELETE         33561
#define ID_MENU_EFN_NULLS_CREATE_NEW    33564
#define ID_MENU_SCN_CAMERA_OBJ_EDIT_POS 33566
#define ID_MENU_SCN_FINISH_OBJECT_POS_EDITING 33568
#define ID_MENU_SCN_EDIT_DUDE_POS       33570
#define ID_Menu33572                    33572
#define ID_MENU_SEL_GEOM_BIND2CAM       33576
#define ID_MENU_SEL_GEOM_CONNECT_TRIS   33577
#define ID_TEMP_ADDLOD                  33578
#define ID_MENU_BATCHCONVERTATION_XSI2MESHLISTEFN 33581
#define ID_MENU_BATCHCONVERTATION_ERRORCORRECTION 33582
#define ID_TEMP_SHOWEXPLORER            33585
#define ID_TEMP_HIDEEXPLORER            33586
#define ID_ACCL_TOGGLE_EXPLORER         33587
#define ID_MENU_SEL_GEOM_MERGE_POINTS   33589
#define ID_MENU_SCN_CAMERA_OBJ_DELETE   33591
#define ID_ACCL_CENTER_CAM_ON_OBJ_ALL_VIEWS 33592
#define ID_MENU_CROP_TOOL               33595
#define ID_Menu33596                    33596
#define ID_Menu33597                    33597
#define ID_ACCELERATOR_LUA_BINDS        33598
#define ID_ACCL_REFRESH_FUNC_BINDINGS   33600
#define ID_MENU_ANIM_DEGRADE_TOOL       33603
#define ID_MENU_HACK_TRANSLATE_SCENE    33605
#define ID_MENU_SCN_LIGHT_DUPLICATE     33610
#define ID_ACCL_GO2DEF                  33611
#define ID_LIGHTS_CREATENEW             33613
#define ID_Menu33616                    33616
#define ID_MENU_SCN_LIGHTS_CREATE_OMNI  33617
#define ID_MENU_SCN_LIGHTS_CREATE_DIRECTIONAL 33618
#define ID_MENU_EFN_NULLS_DELETE_ALL    33621
#define ID_MENU_EFN_MESH_DELETE         33623
#define ID_MENU_ROTATE_Y_180            33626
#define ID_TRANSFORMATIONS_ROTATION     33627
#define ID_MENU_ROTATE_Y_90             33632
#define ID_MENU_ROTATE_Z_90             33633
#define ID_MENU_SCN_MESHES_CREATE_BOX_TESS 33635
#define ID_CREATEOBJECT_CONE            33638
#define ID_MENU_SCN_MESHES_CREATE_CYLINDER_TESS 33639
#define ID_MENU_HIDEBYTYPE_DYNFLOORS    33642
#define ID_MENU_HIDEBYTYPE_SHADOW_RECEIVERS 33643
#define ID_MENU_SHOWBYTYPE_DYNFLOORS    33646
#define ID_MENU_SHOWBYTYPE_SHADOW_RECEIVERS 33647
#define ID_MENU_ROTATE_X_90             33649
#define ID_MENU_SCALE_Z_OFFSETS         33650

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         33651
#define _APS_NEXT_CONTROL_VALUE         1181
#define _APS_NEXT_SYMED_VALUE           149
#endif
#endif
