foldersTree = gFld("<b>Softimage|FTK</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("CASCIIFilter", "", "classCASCIIFilter.html"))
       insDoc(aux1, gLnk("CBINFilter", "", "classCBINFilter.html"))
       insDoc(aux1, gLnk("CBufferFilter", "", "classCBufferFilter.html"))
       insDoc(aux1, gLnk("CdotXSIDict", "", "classCdotXSIDict.html"))
       insDoc(aux1, gLnk("CdotXSIParam", "", "classCdotXSIParam.html"))
       insDoc(aux1, gLnk("CdotXSIParams", "", "classCdotXSIParams.html"))
       insDoc(aux1, gLnk("CdotXSITemplate", "", "classCdotXSITemplate.html"))
       insDoc(aux1, gLnk("CdotXSITemplates", "", "classCdotXSITemplates.html"))
       insDoc(aux1, gLnk("CEnumDictionary", "", "classCEnumDictionary.html"))
       insDoc(aux1, gLnk("CLegacyFilter", "", "classCLegacyFilter.html"))
       insDoc(aux1, gLnk("CSIAccumString", "", "classCSIAccumString.html"))
       insDoc(aux1, gLnk("CSIBCArray", "", "classCSIBCArray.html"))
       insDoc(aux1, gLnk("CSIBCColorb", "", "classCSIBCColorb.html"))
       insDoc(aux1, gLnk("CSIBCColorf", "", "classCSIBCColorf.html"))
       insDoc(aux1, gLnk("CSIBCFileRam", "", "classCSIBCFileRam.html"))
       insDoc(aux1, gLnk("CSIBCMatrix33d", "", "classCSIBCMatrix33d.html"))
       insDoc(aux1, gLnk("CSIBCMatrix44d", "", "classCSIBCMatrix44d.html"))
       insDoc(aux1, gLnk("CSIBCMatrix4x4", "", "classCSIBCMatrix4x4.html"))
       insDoc(aux1, gLnk("CSIBCMatrixMNd", "", "classCSIBCMatrixMNd.html"))
       insDoc(aux1, gLnk("CSIBCNode", "", "classCSIBCNode.html"))
       insDoc(aux1, gLnk("CSIBCPixMapDriver", "", "classCSIBCPixMapDriver.html"))
       insDoc(aux1, gLnk("CSIBCQuaternion", "", "classCSIBCQuaternion.html"))
       insDoc(aux1, gLnk("CSIBCQuaterniond", "", "classCSIBCQuaterniond.html"))
       insDoc(aux1, gLnk("CSIBCRotationd", "", "classCSIBCRotationd.html"))
       insDoc(aux1, gLnk("CSIBCRotMatd", "", "classCSIBCRotMatd.html"))
       insDoc(aux1, gLnk("CSIBCSearchPath", "", "classCSIBCSearchPath.html"))
       insDoc(aux1, gLnk("CSIBCString", "", "classCSIBCString.html"))
       insDoc(aux1, gLnk("CSIBCTransfod", "", "classCSIBCTransfod.html"))
       insDoc(aux1, gLnk("CSIBCUserData", "", "classCSIBCUserData.html"))
       insDoc(aux1, gLnk("CSIBCVector2D", "", "classCSIBCVector2D.html"))
       insDoc(aux1, gLnk("CSIBCVector2Dd", "", "classCSIBCVector2Dd.html"))
       insDoc(aux1, gLnk("CSIBCVector3D", "", "classCSIBCVector3D.html"))
       insDoc(aux1, gLnk("CSIBCVector3Dd", "", "classCSIBCVector3Dd.html"))
       insDoc(aux1, gLnk("CSIBCVector4D", "", "classCSIBCVector4D.html"))
       insDoc(aux1, gLnk("CSIBCVector4Dd", "", "classCSIBCVector4Dd.html"))
       insDoc(aux1, gLnk("CSIBCVectorwd", "", "classCSIBCVectorwd.html"))
       insDoc(aux1, gLnk("CSIBCXfoMatd", "", "classCSIBCXfoMatd.html"))
       insDoc(aux1, gLnk("CSIILBMPFileDriver", "", "classCSIILBMPFileDriver.html"))
       insDoc(aux1, gLnk("CSIILGIFFileDriver", "", "classCSIILGIFFileDriver.html"))
       insDoc(aux1, gLnk("CSIILJPGFileDriver", "", "classCSIILJPGFileDriver.html"))
       insDoc(aux1, gLnk("CSIILPICFileDriver", "", "classCSIILPICFileDriver.html"))
       insDoc(aux1, gLnk("CSIILPPMFileDriver", "", "classCSIILPPMFileDriver.html"))
       insDoc(aux1, gLnk("CSIILTGAFileDriver", "", "classCSIILTGAFileDriver.html"))
       insDoc(aux1, gLnk("CSLAction", "", "classCSLAction.html"))
       insDoc(aux1, gLnk("CSLActionClip", "", "classCSLActionClip.html"))
       insDoc(aux1, gLnk("CSLActionFCurve", "", "classCSLActionFCurve.html"))
       insDoc(aux1, gLnk("CSLAmbience", "", "classCSLAmbience.html"))
       insDoc(aux1, gLnk("CSLAngle", "", "classCSLAngle.html"))
       insDoc(aux1, gLnk("CSLAnimatableType", "", "classCSLAnimatableType.html"))
       insDoc(aux1, gLnk("CSLArrayProxy", "", "classCSLArrayProxy.html"))
       insDoc(aux1, gLnk("CSLBaseFCurve", "", "classCSLBaseFCurve.html"))
       insDoc(aux1, gLnk("CSLBaseKey", "", "structCSLBaseKey.html"))
       insDoc(aux1, gLnk("CSLBaseMaterial", "", "classCSLBaseMaterial.html"))
       insDoc(aux1, gLnk("CSLBaseShape", "", "classCSLBaseShape.html"))
       insDoc(aux1, gLnk("CSLBoolProxy", "", "classCSLBoolProxy.html"))
       insDoc(aux1, gLnk("CSLByteProxy", "", "classCSLByteProxy.html"))
       insDoc(aux1, gLnk("CSLCamera", "", "classCSLCamera.html"))
       insDoc(aux1, gLnk("CSLCluster", "", "classCSLCluster.html"))
       insDoc(aux1, gLnk("CSLColorRGBAProxy", "", "classCSLColorRGBAProxy.html"))
       insDoc(aux1, gLnk("CSLColorRGBProxy", "", "classCSLColorRGBProxy.html"))
       insDoc(aux1, gLnk("CSLConnectionPoint", "", "classCSLConnectionPoint.html"))
       insDoc(aux1, gLnk("CSLConstantKey", "", "structCSLConstantKey.html"))
       insDoc(aux1, gLnk("CSLConstrainableType", "", "classCSLConstrainableType.html"))
       insDoc(aux1, gLnk("CSLConstraint", "", "classCSLConstraint.html"))
       insDoc(aux1, gLnk("CSLCoordinateSystem", "", "classCSLCoordinateSystem.html"))
       insDoc(aux1, gLnk("CSLCubicKey", "", "structCSLCubicKey.html"))
       insDoc(aux1, gLnk("CSLCurveList", "", "classCSLCurveList.html"))
       insDoc(aux1, gLnk("CSLCustomParameter", "", "classCSLCustomParameter.html"))
       insDoc(aux1, gLnk("CSLCustomPSet", "", "classCSLCustomPSet.html"))
       insDoc(aux1, gLnk("CSLDirectionalLight", "", "classCSLDirectionalLight.html"))
       insDoc(aux1, gLnk("CSLDoubleProxy", "", "classCSLDoubleProxy.html"))
       insDoc(aux1, gLnk("CSLEnumProxy", "", "classCSLEnumProxy.html"))
       insDoc(aux1, gLnk("CSLEnvelope", "", "classCSLEnvelope.html"))
       insDoc(aux1, gLnk("CSLEnvelopeList", "", "classCSLEnvelopeList.html"))
       insDoc(aux1, gLnk("CSLExtrapolation", "", "classCSLExtrapolation.html"))
       insDoc(aux1, gLnk("CSLFCurve", "", "classCSLFCurve.html"))
       insDoc(aux1, gLnk("CSLFileInfo", "", "classCSLFileInfo.html"))
       insDoc(aux1, gLnk("CSLFloatProxy", "", "classCSLFloatProxy.html"))
       insDoc(aux1, gLnk("CSLFog", "", "classCSLFog.html"))
       insDoc(aux1, gLnk("CSLFXOperator", "", "classCSLFXOperator.html"))
       insDoc(aux1, gLnk("CSLFXOperatorConnection", "", "classCSLFXOperatorConnection.html"))
       insDoc(aux1, gLnk("CSLFXTree", "", "classCSLFXTree.html"))
       insDoc(aux1, gLnk("CSLGeometry", "", "classCSLGeometry.html"))
       insDoc(aux1, gLnk("CSLGlobalMaterial", "", "classCSLGlobalMaterial.html"))
       insDoc(aux1, gLnk("CSLHermiteKey", "", "structCSLHermiteKey.html"))
       insDoc(aux1, gLnk("CSLIK", "", "classCSLIK.html"))
       insDoc(aux1, gLnk("CSLIKEffector", "", "classCSLIKEffector.html"))
       insDoc(aux1, gLnk("CSLIKJoint", "", "classCSLIKJoint.html"))
       insDoc(aux1, gLnk("CSLIKRoot", "", "classCSLIKRoot.html"))
       insDoc(aux1, gLnk("CSLImage", "", "classCSLImage.html"))
       insDoc(aux1, gLnk("CSLImageClip", "", "classCSLImageClip.html"))
       insDoc(aux1, gLnk("CSLImageData", "", "classCSLImageData.html"))
       insDoc(aux1, gLnk("CSLImageFX", "", "classCSLImageFX.html"))
       insDoc(aux1, gLnk("CSLImageLibrary", "", "classCSLImageLibrary.html"))
       insDoc(aux1, gLnk("CSLInfiniteLight", "", "classCSLInfiniteLight.html"))
       insDoc(aux1, gLnk("CSLInstance", "", "classCSLInstance.html"))
       insDoc(aux1, gLnk("CSLIntProxy", "", "classCSLIntProxy.html"))
       insDoc(aux1, gLnk("CSLLight", "", "classCSLLight.html"))
       insDoc(aux1, gLnk("CSLLightInfo", "", "classCSLLightInfo.html"))
       insDoc(aux1, gLnk("CSLLinearKey", "", "structCSLLinearKey.html"))
       insDoc(aux1, gLnk("CSLLogger", "", "classCSLLogger.html"))
       insDoc(aux1, gLnk("CSLLongProxy", "", "classCSLLongProxy.html"))
       insDoc(aux1, gLnk("CSLMaterial", "", "classCSLMaterial.html"))
       insDoc(aux1, gLnk("CSLMaterialLibrary", "", "classCSLMaterialLibrary.html"))
       insDoc(aux1, gLnk("CSLMatrix4x4Proxy", "", "classCSLMatrix4x4Proxy.html"))
       insDoc(aux1, gLnk("CSLMesh", "", "classCSLMesh.html"))
       insDoc(aux1, gLnk("CSLMixer", "", "classCSLMixer.html"))
       insDoc(aux1, gLnk("CSLModel", "", "classCSLModel.html"))
       insDoc(aux1, gLnk("CSLNull", "", "classCSLNull.html"))
       insDoc(aux1, gLnk("CSLNurbsCurve", "", "classCSLNurbsCurve.html"))
       insDoc(aux1, gLnk("CSLNurbsProjection", "", "classCSLNurbsProjection.html"))
       insDoc(aux1, gLnk("CSLNurbsSurface", "", "classCSLNurbsSurface.html"))
       insDoc(aux1, gLnk("CSLNurbsTrim", "", "classCSLNurbsTrim.html"))
       insDoc(aux1, gLnk("CSLPatchSurface", "", "classCSLPatchSurface.html"))
       insDoc(aux1, gLnk("CSLPointLight", "", "classCSLPointLight.html"))
       insDoc(aux1, gLnk("CSLPolygonList", "", "classCSLPolygonList.html"))
       insDoc(aux1, gLnk("CSLPrimitive", "", "classCSLPrimitive.html"))
       insDoc(aux1, gLnk("CSLScene", "", "classCSLScene.html"))
       insDoc(aux1, gLnk("CSLSceneInfo", "", "classCSLSceneInfo.html"))
       insDoc(aux1, gLnk("CSLShaderConnectionPoint", "", "classCSLShaderConnectionPoint.html"))
       insDoc(aux1, gLnk("CSLShaderInstanceData", "", "classCSLShaderInstanceData.html"))
       insDoc(aux1, gLnk("CSLShape", "", "classCSLShape.html"))
       insDoc(aux1, gLnk("CSLShape_35", "", "classCSLShape__35.html"))
       insDoc(aux1, gLnk("CSLShapeAnimation", "", "classCSLShapeAnimation.html"))
       insDoc(aux1, gLnk("CSLShortProxy", "", "classCSLShortProxy.html"))
       insDoc(aux1, gLnk("CSLSpotLight", "", "classCSLSpotLight.html"))
       insDoc(aux1, gLnk("CSLStaticValue", "", "classCSLStaticValue.html"))
       insDoc(aux1, gLnk("CSLStrEnumProxy", "", "classCSLStrEnumProxy.html"))
       insDoc(aux1, gLnk("CSLStringProxy", "", "classCSLStringProxy.html"))
       insDoc(aux1, gLnk("CSLSurfaceMesh", "", "classCSLSurfaceMesh.html"))
       insDoc(aux1, gLnk("CSLTemplate", "", "classCSLTemplate.html"))
       insDoc(aux1, gLnk("CSLTexture2D", "", "classCSLTexture2D.html"))
       insDoc(aux1, gLnk("CSLTimeControl", "", "classCSLTimeControl.html"))
       insDoc(aux1, gLnk("CSLTrack", "", "classCSLTrack.html"))
       insDoc(aux1, gLnk("CSLTransform", "", "classCSLTransform.html"))
       insDoc(aux1, gLnk("CSLTriangleList", "", "classCSLTriangleList.html"))
       insDoc(aux1, gLnk("CSLTriangleStrip", "", "classCSLTriangleStrip.html"))
       insDoc(aux1, gLnk("CSLTriangleStripList", "", "classCSLTriangleStripList.html"))
       insDoc(aux1, gLnk("CSLUByteProxy", "", "classCSLUByteProxy.html"))
       insDoc(aux1, gLnk("CSLULongProxy", "", "classCSLULongProxy.html"))
       insDoc(aux1, gLnk("CSLUnresolvedElement", "", "classCSLUnresolvedElement.html"))
       insDoc(aux1, gLnk("CSLUserData", "", "classCSLUserData.html"))
       insDoc(aux1, gLnk("CSLUserDataList", "", "classCSLUserDataList.html"))
       insDoc(aux1, gLnk("CSLUVCoordArray", "", "classCSLUVCoordArray.html"))
       insDoc(aux1, gLnk("CSLVariantParameter", "", "classCSLVariantParameter.html"))
       insDoc(aux1, gLnk("CSLVariantProxy", "", "classCSLVariantProxy.html"))
       insDoc(aux1, gLnk("CSLVector3DProxy", "", "classCSLVector3DProxy.html"))
       insDoc(aux1, gLnk("CSLVisibility", "", "classCSLVisibility.html"))
       insDoc(aux1, gLnk("CSLXSICustomParamInfo", "", "classCSLXSICustomParamInfo.html"))
       insDoc(aux1, gLnk("CSLXSIMaterial", "", "classCSLXSIMaterial.html"))
       insDoc(aux1, gLnk("CSLXSIMaterialInfo", "", "classCSLXSIMaterialInfo.html"))
       insDoc(aux1, gLnk("CSLXSIShader", "", "classCSLXSIShader.html"))
       insDoc(aux1, gLnk("CXSIFilter", "", "classCXSIFilter.html"))
       insDoc(aux1, gLnk("CXSIParser", "", "classCXSIParser.html"))
       insDoc(aux1, gLnk("CXSIReturn", "", "classCXSIReturn.html"))
       insDoc(aux1, gLnk("SLContext", "", "structSLContext.html"))
       insDoc(aux1, gLnk("SLIndexedColor", "", "structSLIndexedColor.html"))
       insDoc(aux1, gLnk("SLIndexedVector2D", "", "structSLIndexedVector2D.html"))
       insDoc(aux1, gLnk("SLIndexedVector3D", "", "structSLIndexedVector3D.html"))
       insDoc(aux1, gLnk("SLTemplateCallback", "", "structSLTemplateCallback.html"))
       insDoc(aux1, gLnk("SLVertexWeight", "", "structSLVertexWeight.html"))
       insDoc(aux1, gLnk("StrLessPred", "", "structStrLessPred.html"))
       insDoc(aux1, gLnk("TinyVariant", "", "structTinyVariant.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("_BmpHeader", "", ""))
       insDoc(aux1, gLnk("_BmpInfo", "", ""))
       insDoc(aux1, gLnk("_WinInfoHeader", "", ""))
       insDoc(aux1, gLnk("CdotXSIDict", "", "classCdotXSIDict.html"))
       insDoc(aux1, gLnk("CdotXSIParams", "", "classCdotXSIParams.html"))
       insDoc(aux1, gLnk("CdotXSITemplates", "", "classCdotXSITemplates.html"))
       insDoc(aux1, gLnk("CEnumDictionary", "", "classCEnumDictionary.html"))
       insDoc(aux1, gLnk("CSIAccumString", "", "classCSIAccumString.html"))
       insDoc(aux1, gLnk("CSIBCArray", "", "classCSIBCArray.html"))
       insDoc(aux1, gLnk("CSIBCColorb", "", "classCSIBCColorb.html"))
       insDoc(aux1, gLnk("CSIBCColorf", "", "classCSIBCColorf.html"))
       insDoc(aux1, gLnk("CSIBCFileRam", "", "classCSIBCFileRam.html"))
  aux2 = insFld(aux1, gFld("CSIBCMatrix33d", "", "classCSIBCMatrix33d.html"))
         insDoc(aux2, gLnk("CSIBCRotMatd", "", "classCSIBCRotMatd.html"))
  aux2 = insFld(aux1, gFld("CSIBCMatrix44d", "", "classCSIBCMatrix44d.html"))
         insDoc(aux2, gLnk("CSIBCXfoMatd", "", "classCSIBCXfoMatd.html"))
       insDoc(aux1, gLnk("CSIBCMatrix4x4", "", "classCSIBCMatrix4x4.html"))
       insDoc(aux1, gLnk("CSIBCMatrixMNd", "", "classCSIBCMatrixMNd.html"))
  aux2 = insFld(aux1, gFld("CSIBCNode", "", "classCSIBCNode.html"))
         insDoc(aux2, gLnk("CdotXSIParam", "", "classCdotXSIParam.html"))
         insDoc(aux2, gLnk("CdotXSITemplate", "", "classCdotXSITemplate.html"))
         insDoc(aux2, gLnk("CSIBCPixMap", "", ""))
    aux3 = insFld(aux2, gFld("CSLTemplate", "", "classCSLTemplate.html"))
           insDoc(aux3, gLnk("CSLAction", "", "classCSLAction.html"))
           insDoc(aux3, gLnk("CSLActionClip", "", "classCSLActionClip.html"))
           insDoc(aux3, gLnk("CSLAmbience", "", "classCSLAmbience.html"))
           insDoc(aux3, gLnk("CSLAngle", "", "classCSLAngle.html"))
      aux4 = insFld(aux3, gFld("CSLBaseFCurve", "", "classCSLBaseFCurve.html"))
             insDoc(aux4, gLnk("CSLActionFCurve", "", "classCSLActionFCurve.html"))
             insDoc(aux4, gLnk("CSLFCurve", "", "classCSLFCurve.html"))
      aux4 = insFld(aux3, gFld("CSLBaseMaterial", "", "classCSLBaseMaterial.html"))
             insDoc(aux4, gLnk("CSLMaterial", "", "classCSLMaterial.html"))
             insDoc(aux4, gLnk("CSLXSIMaterial", "", "classCSLXSIMaterial.html"))
      aux4 = insFld(aux3, gFld("CSLBaseShape", "", "classCSLBaseShape.html"))
             insDoc(aux4, gLnk("CSLShape", "", "classCSLShape.html"))
             insDoc(aux4, gLnk("CSLShape_35", "", "classCSLShape__35.html"))
           insDoc(aux3, gLnk("CSLCluster", "", "classCSLCluster.html"))
           insDoc(aux3, gLnk("CSLConstraint", "", "classCSLConstraint.html"))
           insDoc(aux3, gLnk("CSLCoordinateSystem", "", "classCSLCoordinateSystem.html"))
           insDoc(aux3, gLnk("CSLCustomPSet", "", "classCSLCustomPSet.html"))
           insDoc(aux3, gLnk("CSLEnvelope", "", "classCSLEnvelope.html"))
           insDoc(aux3, gLnk("CSLEnvelopeList", "", "classCSLEnvelopeList.html"))
           insDoc(aux3, gLnk("CSLExtrapolation", "", "classCSLExtrapolation.html"))
           insDoc(aux3, gLnk("CSLFileInfo", "", "classCSLFileInfo.html"))
           insDoc(aux3, gLnk("CSLFog", "", "classCSLFog.html"))
           insDoc(aux3, gLnk("CSLFXOperator", "", "classCSLFXOperator.html"))
           insDoc(aux3, gLnk("CSLFXTree", "", "classCSLFXTree.html"))
           insDoc(aux3, gLnk("CSLGlobalMaterial", "", "classCSLGlobalMaterial.html"))
           insDoc(aux3, gLnk("CSLImage", "", "classCSLImage.html"))
           insDoc(aux3, gLnk("CSLImageClip", "", "classCSLImageClip.html"))
           insDoc(aux3, gLnk("CSLImageData", "", "classCSLImageData.html"))
           insDoc(aux3, gLnk("CSLImageFX", "", "classCSLImageFX.html"))
           insDoc(aux3, gLnk("CSLImageLibrary", "", "classCSLImageLibrary.html"))
           insDoc(aux3, gLnk("CSLLightInfo", "", "classCSLLightInfo.html"))
           insDoc(aux3, gLnk("CSLMaterialLibrary", "", "classCSLMaterialLibrary.html"))
           insDoc(aux3, gLnk("CSLMixer", "", "classCSLMixer.html"))
           insDoc(aux3, gLnk("CSLModel", "", "classCSLModel.html"))
           insDoc(aux3, gLnk("CSLNurbsProjection", "", "classCSLNurbsProjection.html"))
           insDoc(aux3, gLnk("CSLNurbsTrim", "", "classCSLNurbsTrim.html"))
           insDoc(aux3, gLnk("CSLPolygonList", "", "classCSLPolygonList.html"))
      aux4 = insFld(aux3, gFld("CSLPrimitive", "", "classCSLPrimitive.html"))
             insDoc(aux4, gLnk("CSLCamera", "", "classCSLCamera.html"))
             insDoc(aux4, gLnk("CSLCurveList", "", "classCSLCurveList.html"))
        aux5 = insFld(aux4, gFld("CSLGeometry", "", "classCSLGeometry.html"))
               insDoc(aux5, gLnk("CSLMesh", "", "classCSLMesh.html"))
               insDoc(aux5, gLnk("CSLNurbsCurve", "", "classCSLNurbsCurve.html"))
               insDoc(aux5, gLnk("CSLNurbsSurface", "", "classCSLNurbsSurface.html"))
               insDoc(aux5, gLnk("CSLPatchSurface", "", "classCSLPatchSurface.html"))
        aux5 = insFld(aux4, gFld("CSLIK", "", "classCSLIK.html"))
               insDoc(aux5, gLnk("CSLIKEffector", "", "classCSLIKEffector.html"))
               insDoc(aux5, gLnk("CSLIKJoint", "", "classCSLIKJoint.html"))
               insDoc(aux5, gLnk("CSLIKRoot", "", "classCSLIKRoot.html"))
             insDoc(aux4, gLnk("CSLInstance", "", "classCSLInstance.html"))
        aux5 = insFld(aux4, gFld("CSLLight", "", "classCSLLight.html"))
               insDoc(aux5, gLnk("CSLDirectionalLight", "", "classCSLDirectionalLight.html"))
               insDoc(aux5, gLnk("CSLInfiniteLight", "", "classCSLInfiniteLight.html"))
               insDoc(aux5, gLnk("CSLPointLight", "", "classCSLPointLight.html"))
               insDoc(aux5, gLnk("CSLSpotLight", "", "classCSLSpotLight.html"))
             insDoc(aux4, gLnk("CSLNull", "", "classCSLNull.html"))
             insDoc(aux4, gLnk("CSLSurfaceMesh", "", "classCSLSurfaceMesh.html"))
           insDoc(aux3, gLnk("CSLSceneInfo", "", "classCSLSceneInfo.html"))
           insDoc(aux3, gLnk("CSLShaderInstanceData", "", "classCSLShaderInstanceData.html"))
           insDoc(aux3, gLnk("CSLShapeAnimation", "", "classCSLShapeAnimation.html"))
           insDoc(aux3, gLnk("CSLStaticValue", "", "classCSLStaticValue.html"))
           insDoc(aux3, gLnk("CSLTexture2D", "", "classCSLTexture2D.html"))
           insDoc(aux3, gLnk("CSLTimeControl", "", "classCSLTimeControl.html"))
           insDoc(aux3, gLnk("CSLTrack", "", "classCSLTrack.html"))
           insDoc(aux3, gLnk("CSLTransform", "", "classCSLTransform.html"))
           insDoc(aux3, gLnk("CSLTriangleList", "", "classCSLTriangleList.html"))
           insDoc(aux3, gLnk("CSLTriangleStrip", "", "classCSLTriangleStrip.html"))
           insDoc(aux3, gLnk("CSLTriangleStripList", "", "classCSLTriangleStripList.html"))
           insDoc(aux3, gLnk("CSLUserData", "", "classCSLUserData.html"))
           insDoc(aux3, gLnk("CSLUserDataList", "", "classCSLUserDataList.html"))
           insDoc(aux3, gLnk("CSLVisibility", "", "classCSLVisibility.html"))
           insDoc(aux3, gLnk("CSLXSICustomParamInfo", "", "classCSLXSICustomParamInfo.html"))
           insDoc(aux3, gLnk("CSLXSIMaterialInfo", "", "classCSLXSIMaterialInfo.html"))
           insDoc(aux3, gLnk("CSLXSIShader", "", "classCSLXSIShader.html"))
  aux2 = insFld(aux1, gFld("CSIBCPixMapDriver", "", "classCSIBCPixMapDriver.html"))
         insDoc(aux2, gLnk("CSIILBMPFileDriver", "", "classCSIILBMPFileDriver.html"))
         insDoc(aux2, gLnk("CSIILGIFFileDriver", "", "classCSIILGIFFileDriver.html"))
         insDoc(aux2, gLnk("CSIILJPGFileDriver", "", "classCSIILJPGFileDriver.html"))
         insDoc(aux2, gLnk("CSIILPICFileDriver", "", "classCSIILPICFileDriver.html"))
         insDoc(aux2, gLnk("CSIILPPMFileDriver", "", "classCSIILPPMFileDriver.html"))
         insDoc(aux2, gLnk("CSIILTGAFileDriver", "", "classCSIILTGAFileDriver.html"))
       insDoc(aux1, gLnk("CSIBCQuaternion", "", "classCSIBCQuaternion.html"))
       insDoc(aux1, gLnk("CSIBCQuaterniond", "", "classCSIBCQuaterniond.html"))
       insDoc(aux1, gLnk("CSIBCRotationd", "", "classCSIBCRotationd.html"))
       insDoc(aux1, gLnk("CSIBCSearchPath", "", "classCSIBCSearchPath.html"))
       insDoc(aux1, gLnk("CSIBCString", "", "classCSIBCString.html"))
       insDoc(aux1, gLnk("CSIBCTransfod", "", "classCSIBCTransfod.html"))
       insDoc(aux1, gLnk("CSIBCUserData", "", "classCSIBCUserData.html"))
       insDoc(aux1, gLnk("CSIBCVector2D", "", "classCSIBCVector2D.html"))
       insDoc(aux1, gLnk("CSIBCVector2Dd", "", "classCSIBCVector2Dd.html"))
       insDoc(aux1, gLnk("CSIBCVector3D", "", "classCSIBCVector3D.html"))
       insDoc(aux1, gLnk("CSIBCVector3Dd", "", "classCSIBCVector3Dd.html"))
       insDoc(aux1, gLnk("CSIBCVector4D", "", "classCSIBCVector4D.html"))
       insDoc(aux1, gLnk("CSIBCVector4Dd", "", "classCSIBCVector4Dd.html"))
       insDoc(aux1, gLnk("CSIBCVectorwd", "", "classCSIBCVectorwd.html"))
  aux2 = insFld(aux1, gFld("CSLAnimatableType", "", "classCSLAnimatableType.html"))
         insDoc(aux2, gLnk("CSLBoolProxy", "", "classCSLBoolProxy.html"))
         insDoc(aux2, gLnk("CSLByteProxy", "", "classCSLByteProxy.html"))
         insDoc(aux2, gLnk("CSLDoubleProxy", "", "classCSLDoubleProxy.html"))
         insDoc(aux2, gLnk("CSLEnumProxy", "", "classCSLEnumProxy.html"))
         insDoc(aux2, gLnk("CSLFloatProxy", "", "classCSLFloatProxy.html"))
         insDoc(aux2, gLnk("CSLIntProxy", "", "classCSLIntProxy.html"))
         insDoc(aux2, gLnk("CSLLongProxy", "", "classCSLLongProxy.html"))
         insDoc(aux2, gLnk("CSLShortProxy", "", "classCSLShortProxy.html"))
         insDoc(aux2, gLnk("CSLStrEnumProxy", "", "classCSLStrEnumProxy.html"))
         insDoc(aux2, gLnk("CSLUByteProxy", "", "classCSLUByteProxy.html"))
         insDoc(aux2, gLnk("CSLULongProxy", "", "classCSLULongProxy.html"))
    aux3 = insFld(aux2, gFld("CSLVariantParameter", "", "classCSLVariantParameter.html"))
           insDoc(aux3, gLnk("CSLCustomParameter", "", "classCSLCustomParameter.html"))
       insDoc(aux1, gLnk("CSLAnimatableVector", "", ""))
       insDoc(aux1, gLnk("CSLArrayProxy", "", "classCSLArrayProxy.html"))
  aux2 = insFld(aux1, gFld("CSLBaseKey", "", "structCSLBaseKey.html"))
         insDoc(aux2, gLnk("CSLConstantKey", "", "structCSLConstantKey.html"))
         insDoc(aux2, gLnk("CSLCubicKey", "", "structCSLCubicKey.html"))
         insDoc(aux2, gLnk("CSLHermiteKey", "", "structCSLHermiteKey.html"))
         insDoc(aux2, gLnk("CSLLinearKey", "", "structCSLLinearKey.html"))
  aux2 = insFld(aux1, gFld("CSLColorRGBProxy", "", "classCSLColorRGBProxy.html"))
         insDoc(aux2, gLnk("CSLColorRGBAProxy", "", "classCSLColorRGBAProxy.html"))
  aux2 = insFld(aux1, gFld("CSLConnectionPoint", "", "classCSLConnectionPoint.html"))
         insDoc(aux2, gLnk("CSLShaderConnectionPoint", "", "classCSLShaderConnectionPoint.html"))
  aux2 = insFld(aux1, gFld("CSLConstrainableType", "", "classCSLConstrainableType.html"))
         insDoc(aux2, gLnk("CSLCamera", "", "classCSLCamera.html"))
         insDoc(aux2, gLnk("CSLLight", "", "classCSLLight.html"))
         insDoc(aux2, gLnk("CSLModel", "", "classCSLModel.html"))
       insDoc(aux1, gLnk("CSLFXOperatorConnection", "", "classCSLFXOperatorConnection.html"))
       insDoc(aux1, gLnk("CSLLogger", "", "classCSLLogger.html"))
       insDoc(aux1, gLnk("CSLMatrix4x4Proxy", "", "classCSLMatrix4x4Proxy.html"))
       insDoc(aux1, gLnk("CSLScene", "", "classCSLScene.html"))
       insDoc(aux1, gLnk("CSLStringProxy", "", "classCSLStringProxy.html"))
       insDoc(aux1, gLnk("CSLUnresolvedElement", "", "classCSLUnresolvedElement.html"))
       insDoc(aux1, gLnk("CSLUVCoordArray", "", "classCSLUVCoordArray.html"))
       insDoc(aux1, gLnk("CSLVariantProxy", "", "classCSLVariantProxy.html"))
       insDoc(aux1, gLnk("CSLVector3DProxy", "", "classCSLVector3DProxy.html"))
  aux2 = insFld(aux1, gFld("CXSIFilter", "", "classCXSIFilter.html"))
         insDoc(aux2, gLnk("CASCIIFilter", "", "classCASCIIFilter.html"))
         insDoc(aux2, gLnk("CBINFilter", "", "classCBINFilter.html"))
         insDoc(aux2, gLnk("CBufferFilter", "", "classCBufferFilter.html"))
         insDoc(aux2, gLnk("CLegacyFilter", "", "classCLegacyFilter.html"))
       insDoc(aux1, gLnk("CXSIParser", "", "classCXSIParser.html"))
       insDoc(aux1, gLnk("CXSIReturn", "", "classCXSIReturn.html"))
       insDoc(aux1, gLnk("GIF_Header", "", ""))
       insDoc(aux1, gLnk("GIF_ImageHeader", "", ""))
       insDoc(aux1, gLnk("GIF_OtherData", "", ""))
       insDoc(aux1, gLnk("GIF_TransparencyBlock", "", ""))
       insDoc(aux1, gLnk("Quat", "", ""))
       insDoc(aux1, gLnk("SI_BMPImage", "", ""))
       insDoc(aux1, gLnk("SI_InternalJpegInfo", "", ""))
       insDoc(aux1, gLnk("SI_TargaImage", "", ""))
       insDoc(aux1, gLnk("SIBCNetworkLayer", "", ""))
  aux2 = insFld(aux1, gFld("SIFileInterface", "", ""))
         insDoc(aux2, gLnk("SIFile", "", ""))
       insDoc(aux1, gLnk("SIFilePtr", "", ""))
       insDoc(aux1, gLnk("SINetMsg", "", ""))
       insDoc(aux1, gLnk("SINetMsgFGETC", "", ""))
       insDoc(aux1, gLnk("SINetMsgFGETCAnswer", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileClose", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileCloseAnswer", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileEnd", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileEOF", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileEOFAnswer", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileOpen", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileOpenAnswer", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileRead", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileReadConfirm", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileReadPacket", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileSeek", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileSeekAnswer", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileTell", "", ""))
       insDoc(aux1, gLnk("SINetMsgFileTellAnswer", "", ""))
       insDoc(aux1, gLnk("SINetMsgLoadFile", "", ""))
       insDoc(aux1, gLnk("SINetMsgParamHandle", "", ""))
       insDoc(aux1, gLnk("SINetMsgParamName", "", ""))
       insDoc(aux1, gLnk("SINetMsgSetHostName", "", ""))
       insDoc(aux1, gLnk("SINetMsgSetParamValue", "", ""))
       insDoc(aux1, gLnk("SINetworkProviderInfo", "", ""))
       insDoc(aux1, gLnk("SLContext", "", "structSLContext.html"))
       insDoc(aux1, gLnk("SLIndexedColor", "", "structSLIndexedColor.html"))
       insDoc(aux1, gLnk("SLIndexedVector2D", "", "structSLIndexedVector2D.html"))
       insDoc(aux1, gLnk("SLIndexedVector3D", "", "structSLIndexedVector3D.html"))
       insDoc(aux1, gLnk("SLTemplateCallback", "", "structSLTemplateCallback.html"))
       insDoc(aux1, gLnk("SLTriangle", "", ""))
       insDoc(aux1, gLnk("SLVertexWeight", "", "structSLVertexWeight.html"))
       insDoc(aux1, gLnk("SOFT_Channel", "", ""))
       insDoc(aux1, gLnk("SOFT_Header", "", ""))
       insDoc(aux1, gLnk("StrLessPred", "", "structStrLessPred.html"))
       insDoc(aux1, gLnk("tagVersionInfo", "", ""))
       insDoc(aux1, gLnk("TARGA_Header", "", ""))
       insDoc(aux1, gLnk("TdotXSIDictEntry", "", ""))
       insDoc(aux1, gLnk("TinyVariant", "", "structTinyVariant.html"))
       insDoc(aux1, gLnk("Wildcard", "", ""))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Modules", "", "modules.html"))
       insDoc(aux1, gLnk("Non generic read/write functions for dotXSI 3.5", "", "group__rwfunc__35.html"))
       insDoc(aux1, gLnk("Global dotXSI parameter collections functions", "", "group__glbfunc__param.html"))
       insDoc(aux1, gLnk("Global dotXSI template functions", "", "group__glbfunc__template.html"))
       insDoc(aux1, gLnk("Registration functions for dotXSI 3.0", "", "group__regfunc__30.html"))
       insDoc(aux1, gLnk("Registration functions for dotXSI 3.5", "", "group__regfunc__35.html"))
       insDoc(aux1, gLnk("Registration functions for dotXSI 3.6", "", "group__regfunc__36.html"))
       insDoc(aux1, gLnk("Utility for the parser", "", "group__Utility.html"))
       insDoc(aux1, gLnk("Callbacks for reading/writing", "", "group__Callbacks.html"))
       insDoc(aux1, gLnk("Mathematical functions & constants.", "", "group__mathdef__group.html"))
       insDoc(aux1, gLnk("Utility functions for angles and rotations.", "", "group__rotutil__group.html"))
       insDoc(aux1, gLnk("TransformationFlags", "", "group__TransformationFlags.html"))
       insDoc(aux1, gLnk("FTK error codes", "", "group__siError__group.html"))
       insDoc(aux1, gLnk("Softimage FTK type definitions.", "", "group__sitype__group.html"))
       insDoc(aux1, gLnk("Variant Parameter types", "", "group__vptypes__group.html"))
       insDoc(aux1, gLnk("Variant Parameter Tweak types", "", "group__vtwktypes__group.html"))
       insDoc(aux1, gLnk("FTK utility macros and defines.", "", "group__ftktutil__group.html"))
